// get courses
export const FETCH_MCQs_REQUEST = "FETCH_MCQs_REQUEST";
export const FETCH_MCQs_SUCCESS = "FETCH_MCQs_SUCCESS";
export const FETCH_MCQs_FAILURE = "FETCH_MCQs_FAILURE";

// add courses
export const ADD_MCQ_REQUEST = "ADD_MCQ_REQUEST";
export const ADD_MCQ_SUCCESS = "ADD_MCQ_SUCCESS";
export const ADD_MCQ_FAILURE = "ADD_MCQ_FAILURE";

// UPDATE
export const UPDATE_MCQ_REQUEST = "UPDATE_MCQ_REQUEST";
export const UPDATE_MCQ_SUCCESS = "UPDATE_MCQ_SUCCESS";
export const UPDATE_MCQ_FAILURE = "UPDATE_MCQ_FAILURE";

// DELETE
export const DELETE_MCQ_REQUEST = "DELETE_MCQ_REQUEST";
export const DELETE_MCQ_SUCCESS = "DELETE_MCQ_SUCCESS";
export const DELETE_MCQ_FAILURE = "DELETE_MCQ_FAILURE";