// constants/courses.js

// get courses
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";

// add courses
export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

// UPDATE
export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

// DELETE
export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";
// constants/courses.js

// get courses
export const FETCH_INSTRUCTORS_REQUEST = "FETCH_INSTRUCTORS_REQUEST";
export const FETCH_INSTRUCTORS_SUCCESS = "FETCH_INSTRUCTORS_SUCCESS";
export const FETCH_INSTRUCTORS_FAILURE = "FETCH_INSTRUCTORS_FAILURE";

// add courses
export const ADD_INSTRUCTOR_REQUEST = "ADD_INSTRUCTOR_REQUEST";
export const ADD_INSTRUCTOR_SUCCESS = "ADD_INSTRUCTOR_SUCCESS";
export const ADD_INSTRUCTOR_FAILURE = "ADD_INSTRUCTOR_FAILURE";

// UPDATE
export const UPDATE_INSTRUCTOR_REQUEST = "UPDATE_INSTRUCTOR_REQUEST";
export const UPDATE_INSTRUCTOR_SUCCESS = "UPDATE_INSTRUCTOR_SUCCESS";
export const UPDATE_INSTRUCTOR_FAILURE = "UPDATE_INSTRUCTOR_FAILURE";

// DELETE
export const DELETE_INSTRUCTOR_REQUEST = "DELETE_INSTRUCTOR_REQUEST";
export const DELETE_INSTRUCTOR_SUCCESS = "DELETE_INSTRUCTOR_SUCCESS";
export const DELETE_INSTRUCTOR_FAILURE = "DELETE_INSTRUCTOR_FAILURE";
